### ISSUE TITLE
AttributeError: module 'asyncio.tasks' has no attribute 'all_tasks'

### ISSUE THREAD

**Issue by brianmay** [pgjones/hypercorn#11]
This happens after pushing Ctrl-C to shutdown a server:

```
Traceback (most recent call last):
  File "./bsm3/testing/soap_server/server.py", line 219, in <module>
    app.run(host='0.0.0.0', port=8080, debug=True)
  File "/home/brian/.virtualenvs/bluescope-m3-mw/lib/python3.6/site-packages/quart/app.py", line 1346, in run
    run_single(self, config, loop=loop)
  File "/home/brian/.virtualenvs/bluescope-m3-mw/lib/python3.6/site-packages/hypercorn/asyncio/run.py", line 168, in run_single
    _cancel_all_other_tasks(loop, lifespan_task)
  File "/home/brian/.virtualenvs/bluescope-m3-mw/lib/python3.6/site-packages/hypercorn/asyncio/run.py", line 211, in _cancel_all_other_tasks
    tasks = [task for task in asyncio.tasks.all_tasks(loop) if task != protected_task]
AttributeError: module 'asyncio.tasks' has no attribute 'all_tasks'
```

**Comment by pgjones** [comment]
This should now be fixed, can you upgrade to 0.4.3?

**Comment by brianmay** [comment]
Fast response :-)

Will try, thanks.

**Comment by brianmay** [comment]
Looks fine, closing.
