### ISSUE TITLE
`--quic-bind 0.0.0.0:4433` fails to listen on port 4433 and browser fails to reach my application

### ISSUE THREAD

**Issue by khteh** [pgjones/hypercorn#182]
```
pipenv run hypercorn --reload --quic-bind 0.0.0.0:4433 --certfile server.crt --keyfile server.key --bind 0.0.0.0:8080 src.main:app
```
```
[2024-01-24 13:26:10 +0800] [39801] [INFO] Running on https://0.0.0.0:8080 (CTRL + C to quit)
2024-01-24 13:26:10 INFO     Running on https://0.0.0.0:8080 (CTRL + C to quit)
[2024-01-24 13:26:10 +0800] [39801] [INFO] Running on https://0.0.0.0:4433 (QUIC) (CTRL + C to quit)
2024-01-24 13:26:10 INFO     Running on https://0.0.0.0:4433 (QUIC) (CTRL + C to quit)
```
https://localhost:4433/ fails. What happen?

**Comment by XChikuX** [comment]
This is a long standing bug.

--quic-bind just refuses to be reachable outside localhost. i.e. 0.0.0.0 will fail

**Comment by khteh** [comment]
Any update on this!?! How can I use this library to serve H3!?!

**Comment by pgjones** [comment]
I don't think browsers try HTTP/3 by default, you'll need to serve over HTTP/1 or HTTP/2 and send an alt-serve header. [Here](https://github.com/pgjones/pgjones_dev/blob/c13aefe658d9f784cdbfa7244b45867a02122077/hypercorn.toml#L2) is an example.

**Comment by khteh** [comment]
Now it complains `OSError: [Errno 98] Address already in use`
```
pipenv run hypercorn --config=hypercorn.toml --reload src.main:app
```
There are 3 `bind` configurations in the `.toml` what do `bind` and `insecure_bind` do?

**Comment by khteh** [comment]
I comment out `server_names` as I don't know how useful it is to reach the app from browser. Using the following config,
```
accesslog = "/var/log/pythonrestapi"
errorlog = "/var/log/pythonrestapi"
alt_svc_headers = ["h3=\":443\"; ma=3600, h3-29=\":443\"; ma=3600"]
quic_bind = "0.0.0.0:4433"
bind = "0.0.0.0:4433"
insecure_bind = "0.0.0.0:8080"
certfile = "server.crt"
keyfile = "server.key"
#server_names = ["pythonrestapi"]
worker_class = "trio"
```
I hit the following runtime error:
```
2024-05-29 13:12:17 INFO     Running on https://0.0.0.0:4433 (CTRL + C to quit)
2024-05-29 13:12:17 INFO     Running on http://0.0.0.0:8080 (CTRL + C to quit)
2024-05-29 13:12:17 INFO     Running on https://0.0.0.0:4433 (QUIC) (CTRL + C to quit)
2024-05-29 13:12:26 ERROR    Error in ASGI Framework
Traceback (most recent call last):
  File "/home/khteh/.local/share/virtualenvs/PythonRestAPI-6TwrpjXm/lib/python3.12/site-packages/hypercorn/trio/task_group.py", line 26, in _handle
    await app(scope, receive, send, sync_spawn, call_soon)
  File "/home/khteh/.local/share/virtualenvs/PythonRestAPI-6TwrpjXm/lib/python3.12/site-packages/hypercorn/app_wrappers.py", line 34, in __call__
    await self.app(scope, receive, send)
  File "/home/khteh/.local/share/virtualenvs/PythonRestAPI-6TwrpjXm/lib/python3.12/site-packages/quart/app.py", line 1667, in __call__
    await self.asgi_app(scope, receive, send)
  File "/home/khteh/.local/share/virtualenvs/PythonRestAPI-6TwrpjXm/lib/python3.12/site-packages/quart/app.py", line 1693, in asgi_app
    await asgi_handler(receive, send)
  File "/home/khteh/.local/share/virtualenvs/PythonRestAPI-6TwrpjXm/lib/python3.12/site-packages/quart/asgi.py", line 48, in __call__
    done, pending = await asyncio.wait(
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 463, in wait
    loop = events.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
```

**Comment by khteh** [comment]
Hello, I tried to load `.toml` config file programmatically but it still doesn't work:
```
from hypercorn.config import Config
config = Config()
config.from_toml("/etc/pythonrestapi.toml")

asyncio.run(serve(app, config))
```
This is all I see in the terminal:
```
[2024-06-01 11:28:40 +0800] [100003] [INFO] Running on http://127.0.0.1:8000 (CTRL + C to quit)
2024-06-01 11:28:40 INFO     Running on http://127.0.0.1:8000 (CTRL + C to quit)
```

**Comment by khteh** [comment]
Any update on this? I can see that this project is not actively maintained.

**Comment by khteh** [comment]
What's the plan with this repo? It doesn't seem to be ready for any serious use...?

**Comment by XChikuX** [comment]
No updates in several months. @pgjones I hope you're alright and maintainance will continue soon.

**Comment by khteh** [comment]
More console output with `debug=True`:
```
2025-02-23 17:04:43 INFO     <Server sockets=(<asyncio.TransportSocket fd=11, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000)>,)> is serving
```

**Comment by khteh** [comment]
https://stackoverflow.com/questions/72411373/does-chrome-support-http-3-over-a-port-other-than-443

I switch to low port#:
```
accesslog = "/var/log/pythonrestapi"
errorlog = "/var/log/pythonrestapi"
loglevel = "DEBUG" 
alt_svc_headers = ["h3=\":444\"; ma=3600, h3-29=\":444\"; ma=3600"]
bind = ["0.0.0.0:444"]
quic_bind = ["0.0.0.0:444"]
insecure_bind = ["0.0.0.0:80"]
certfile = "/tmp/server.crt"
keyfile = "/tmp/server.key"
#server_names = ["pythonrestapi"]
worker_class = "asyncio"
workers = 100
```
 and run hypercorn as root but it still runs on http port 8000:
```
Running asyncio...
2025-03-15 11:50:39 INFO     <Server sockets=(<asyncio.TransportSocket fd=7, family=2, type=1, proto=0, laddr=('127.0.0.1', 8000)>,)> is serving
[2025-03-15 11:50:39 +0800] [203616] [INFO] Running on http://127.0.0.1:8000 (CTRL + C to quit)
2025-03-15 11:50:39 INFO     Running on http://127.0.0.1:8000 (CTRL + C to quit)
```

**Comment by khteh** [comment]
> This is a long standing bug.
> 
> --quic-bind just refuses to be reachable outside localhost. i.e. 0.0.0.0 will fail

Is this bug fixed?

**Comment by khteh** [comment]
It works now. I realized that I used hypercorn to start the application which has the programatic hypercorn instance. So, it is double hypercorn. This is bad. The documentation should be clear and programmatically this should throw an exception!

**Comment by XChikuX** [comment]
@khteh Can you give some more details to those who still haven't figured out how to fix this?

**Comment by khteh** [comment]
Sure!
This is how I run my application from BASH shell:
```
pipenv run hypercorn --config=/etc/hypercorn.toml --reload src.main:app
```
`/etc/hypercorn.toml`:
```
accesslog = "/var/log/pythonrestapi"
errorlog = "/var/log/pythonrestapi"
loglevel = "DEBUG" 
alt_svc_headers = ["h3=\":4433\"; ma=3600, h3-29=\":4433\"; ma=3600"]
bind = ["0.0.0.0:4433"]
quic_bind = ["0.0.0.0:4433"]
insecure_bind = ["0.0.0.0:8080"]
certfile = "/tmp/server.crt"
keyfile = "/tmp/server.key"
#server_names = ["pythonrestapi"]
worker_class = "asyncio"
workers = 100
```
`main.py`:
```
app = create_app()
```
`app.py`:
```
app = None
def create_app() -> Quart:
    """
    Create App
    """
    # App initialization
    app = Quart(__name__, template_folder='view/templates', static_url_path='', static_folder='view/static')
```

**Comment by khteh** [comment]
Failed to connect to the `quic_bind` port!

**Comment by khteh** [comment]
```
$ docker run --rm ymuski/curl-http3 curl --http3 --insecure --verbose https://localhost:4433/
* processing: https://localhost:4433/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying [::1]:4433...
* QUIC: connection to ::1 port 4433 refused
* connect to ::1 port 4433 failed: Couldn't connect to server
*   Trying 127.0.0.1:4433...
* QUIC: connection to 127.0.0.1 port 4433 refused
* connect to 127.0.0.1 port 4433 failed: Couldn't connect to server
* Failed to connect to localhost port 4433 after 0 ms: Couldn't connect to server
*   Trying [::1]:4433...
* connect to ::1 port 4433 failed: Connection refused
*   Trying 127.0.0.1:4433...
* connect to 127.0.0.1 port 4433 failed: Connection refused
* Failed to connect to localhost port 4433 after 0 ms: Couldn't connect to server
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection
curl: (7) QUIC: connection to ::1 port 4433 refused
```

**Comment by khteh** [comment]
Close this and use https://github.com/pgjones/hypercorn/issues/290 to track.
