### ISSUE TITLE
Nikto Scan Causes ascii decode issues.

### ISSUE THREAD

**Issue by MisterBianco** [pgjones/hypercorn#2]
When running nikto web application scanner against a quart server I get a decode issue 

```
Exception in callback _SelectorSocketTransport._read_ready()
handle: <Handle _SelectorSocketTransport._read_ready()>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\asyncio\events.py", line 145, in _run
    self._callback(*self._args)
  File "C:\Program Files (x86)\Python36-32\lib\asyncio\selector_events.py", line 730, in _read_ready
    self._protocol.data_received(data)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\hypercorn\run.py", line 51, in data_received
    self._server.data_received(data)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\hypercorn\h11.py", line 56, in data_received
    self.handle_events()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\hypercorn\h11.py", line 84, in handle_events
    self.handle_request(event)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\hypercorn\h11.py", line 163, in handle_request
    'path': unquote(path.decode('ascii')),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 11: ordinal not in range(128)
```

The solution that I believe will work is to modify the file h11.py and on line 163 changing:

```
 'path': unquote(path.decode('ascii')),
```

with:

```
 'path': unquote(path.decode('ascii', 'ignore')),
```

This will make the path not fail on an invalid request.

This isn't a huge issue just something that I think could be fixed however, my suggestion might not be what you want.

If you want me to submit a pull request after testing I should be able to do that later today.

**Comment by pgjones** [comment]
Thanks, I shall look into this.

**Comment by MisterBianco** [comment]
@pgjones well I most certainly agree

**Comment by pgjones** [comment]
h11 0.9.0 has now been released, so this should be fixed in new installs.

**Comment by MisterBianco** [comment]
Woot!
