### ISSUE TITLE
It seems hypercorn is not closing connections properly

### ISSUE THREAD

**Issue by nabheet** [pgjones/hypercorn#241]
We have been getting HTTP 503 errors in our API hosted on GCP Cloud Run. I have been trying to chase this problem down for a long time but I haven't made any progress. I will share my suspicions here and hopefully we can resolve this issue. I used the following sample code and have been testing with `apache-bench` and `curl`. And this is currently limited to HTTP1.1. After starting hypercorn with fast api, I run apache-bench against it. Then I hit CTRL+C in the terminal where hypercorn is running. I am expecting hypercorn to successfully complete all pending connections, return their response, close them, then exit and refuse any new connections.

Sample code:

```
from fastapi import FastAPI
from hypercorn.config import Config
from hypercorn.run import run

app = FastAPI()


@app.get("/")
def root():
    return {"message": "Hello World"}
```

Hypercorn server start with `-w 0`:
```
$ pipenv run hypercorn main:app -b localhost:9002 -w 0
[2024-06-09 16:59:20 -0600] [21585] [INFO] Running on http://127.0.0.1:9002 (CTRL + C to quit)
^C
```

When I run curl like this:
```
$ while [ 0 -eq 0 ]; do curl --ipv4 -sv -H "Connection: close" http://localhost:9002/; if [ $? -ne 0 ]; then echo HELLO; break; fi; done
```

I correctly get the following:
```
... # WHOLE BUNCH OF OUTPUT UNTIL I HIT CTRL+C ON TERMINAL WITH HYPERCORN
< HTTP/1.1 200
< content-length: 25
< content-type: application/json
< date: Sun, 09 Jun 2024 23:40:17 GMT
< server: hypercorn-h11
< Connection: close
<
* Closing connection
{"message":"Hello World"}* Host localhost:9002 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying 127.0.0.1:9002...
* connect to 127.0.0.1 port 9002 from 127.0.0.1 port 50990 failed: Connection refused
* Failed to connect to localhost port 9002 after 0 ms: Couldn't connect to server
* Closing connection
HELLO
```

Whereas if I start it like this:
```
$ pipenv run hypercorn main:app -b localhost:9002
[2024-06-09 17:42:10 -0600] [10806] [INFO] Running on http://127.0.0.1:9002 (CTRL + C to quit)
^C
```

I get the following output:

```
... # WHOLE BUNCH OF OUTPUT UNTIL I HIT CTRL+C ON TERMINAL WITH HYPERCORN
< HTTP/1.1 200
< content-length: 25
< content-type: application/json
< date: Sun, 09 Jun 2024 23:42:21 GMT
< server: hypercorn-h11
< Connection: close
<
* Closing connection
{"message":"Hello World"}* Host localhost:9002 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying 127.0.0.1:9002...
* Connected to localhost (127.0.0.1) port 9002
> GET / HTTP/1.1
> Host: localhost:9002
> User-Agent: curl/8.6.0
> Accept: */*
> Connection: close
>
* Recv failure: Connection reset by peer
* Closing connection
HELLO
```

I have a suspicion that the `Connection reset by peer` error is causing problems for us in GCP Cloud Run which ends up returning a HTTP 503 error to our customers.

I am hoping that it should not return 503. I think it should successfully complete all existing connections and close them, and not accept any new connections. 

Please let me know what you think.

**Comment by nabheet** [comment]
and if I start hypercorn like this:

```
$ pipenv run hypercorn main:app -b localhost:9002 --access-log "-"
```

And I run curl like this:
```
$ while [ 0 -eq 0 ]; do curl --ipv4 -sv http://localhost:9002/; if [ $? -ne 0 ]; then echo HELLO; break; fi; done
```

After a few seconds, I get this error:

```
[2024-06-09 18:40:33 -0600] [40021] [INFO] 127.0.0.1:52769 - - [09/Jun/2024:18:40:33 -0600] "GET / 1.1" 200 25 "-" "curl/8.6.0"
socket.accept() out of system resource
socket: <asyncio.TransportSocket fd=3, family=2, type=1, proto=0, laddr=('127.0.0.1', 9002)>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", line 178, in _accept_connection
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socket.py", line 295, in accept
OSError: [Errno 24] Too many open files
```

**Comment by nabheet** [comment]
but if I run curl like this:

```
$ while [ 0 -eq 0 ]; do curl --ipv4 -sv -H "Connection: close" http://localhost:9002/; if [ $? -ne 0 ]; then echo HELLO; break; fi; done
```

it runs for quite a while.

**Comment by nabheet** [comment]
Looks like this problem was introduced in `v0.17.0`.

**Comment by nabheet** [comment]
so now I am testing `v0.16.0`, I started hypercorn:

```
$ pipenv run hypercorn main:app -b localhost:9002 --access-log "-"
```

I run apache bench like this:
```
$ ab -n 10000000 -c 2 -t300 http://localhost:9002/
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 5000 requests
Completed 10000 requests
Completed 15000 requests
... ->>> GETS STUCK HERE
```

**Comment by nabheet** [comment]
So this time I started the service like this:

```
from fastapi import FastAPI
from hypercorn.config import Config
from hypercorn.run import run

app = FastAPI()


@app.get("/")
def root():
    return {"message": "Hello World"}


def main():
    config = Config()
    config.application_path = "main:app"
    config.bind = ["localhost:9002"]
    config.loglevel = "INFO"
    config.workers = 2
    # config.worker_class = "uvloop"
    config.keep_alive_max_requests = 0
    config.keep_alive_timeout = 0
    config.backlog = 1000
    config.max_app_queue_size = 100
    config.max_requests = 100
    config.max_requests_jitter = 50
    config.accesslog = "-"
    config.errorlog = "-"
    config.debug = True

    return run(config)


if __name__ == "__main__":
    main()
```

With this command:
```
$ pipenv run python main.py
```

and got this error after about 1,000 requests:
```
Error on transport creation for incoming connection
handle_traceback: Handle created at (most recent call last):
  File "/Users/nabheet/code/sample/.venv/lib/python3.12/site-packages/hypercorn/asyncio/run.py", line 234, in _run
    runner.run(main(shutdown_trigger=shutdown_trigger))
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 1979, in _run_once
    handle._run()
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", line 211, in _accept_connection
    self.create_task(accept)
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 458, in create_task
    task = tasks.Task(coro, loop=self, name=name, context=context)
protocol: <asyncio.streams.StreamReaderProtocol object at 0x105a85070>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", line 230, in _accept_connection2
    transport = self._make_socket_transport(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", line 72, in _make_socket_transport
    return _SelectorSocketTransport(self, sock, protocol, waiter,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", line 940, in __init__
    super().__init__(loop, sock, protocol, extra, server)
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/selector_events.py", line 804, in __init__
    self._server._attach()
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 296, in _attach
    assert self._sockets is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by nabheet** [comment]
also, it seems like setting the `keep-alive-timeout` to 0 avoids the `too many files open error`

**Comment by nabheet** [comment]
And when I run `h2load` like this:
```
$ h2load -n 20000 -c 4 --rps 5 http://localhost:9002/ --verbose
```

It always says 4000 succeeded.

```
...
finished in 205.01s, 19.51 req/s, 1.18KB/s
requests: 20000 total, 4004 started, 4000 done, 4000 succeeded, 16000 failed, 16000 errored, 0 timeout
status codes: 4002 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 241.43KB (247228) total, 37.99KB (38902) headers (space savings 90.74%), 97.66KB (100000) data
                     min         max         mean         sd        +/- sd
time for request:     1.61ms     93.27ms      5.30ms     12.82ms    93.78%
time for connect:      243us       330us       290us        37us    50.00%
time to 1st byte:     5.68ms      5.76ms      5.72ms        41us   100.00%
req/s           :       4.88        4.88        4.88        0.00    75.00%
```

**Comment by nabheet** [comment]
when I run curl like this:

```
$ count=0;while [ 0 -eq 0 ]; do curl --ipv4 -sv -H "Connection: close"  http://localhost:9002/ --http2 --http2-prior-knowledge;if [ $? -ne 0 ]; then echo HELLO; break; fi;count=$((count+1)); echo $count; done
```

Curl reports an error after 600 or so requests:
```
* Host localhost:9002 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying 127.0.0.1:9002...
* Connected to localhost (127.0.0.1) port 9002
* [HTTP/2] [1] OPENED stream for http://localhost:9002/
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: http]
* [HTTP/2] [1] [:authority: localhost:9002]
* [HTTP/2] [1] [:path: /]
* [HTTP/2] [1] [user-agent: curl/8.6.0]
* [HTTP/2] [1] [accept: */*]
> GET / HTTP/2
> Host: localhost:9002
> User-Agent: curl/8.6.0
> Accept: */*
> Connection: close
>
* Recv failure: Connection reset by peer
* Failed receiving HTTP2 data: 56(Failure when receiving data from the peer)
* Connection #0 to host localhost left intact
HELLO
```

I am not really sure my test cases are valid but I would think these curl, ab and h2load executions should go on forever or at least finish the total number of requests.

**Comment by nabheet** [comment]
Aite - it seems `h2load` `-n` is related to `keep_alive_max_requests`. Not sure why but `h2load` completes successfully if these two numbers match.

**Comment by nabheet** [comment]
After a lot of googling, I am reasonably confident that this approach causes the event loop to exit cleanly and allow all connection finish before terminating. But I am not sure how to incorporate it in the hypercorn code.

The meat of the functionality is in the `_signal_handler` coroutine(?):

```
import signal
from typing import Any
from fastapi import FastAPI
from hypercorn.config import Config
import asyncio
from hypercorn.asyncio import serve
import logging

app = FastAPI()

logger = logging.getLogger(__name__)

@app.get("/")
def root():
    return {"message": "Hello World"}


def main():
    config = Config()
    config.application_path = "main:app"
    config.bind = ["localhost:9002"]
    config.loglevel = "INFO"
    config.accesslog = "-"
    config.errorlog = "-"

    shutdown_event = asyncio.Event()

    async def _signal_handler(*_: Any) -> None:
        print("HERE!!!!!!!!")
        shutdown_event.set()
        tasks = [t for t in asyncio.all_tasks() if t is not
             asyncio.current_task()]
        logger.info(f"Cancelling {len(tasks)} outstanding tasks")
        await asyncio.gather(*tasks, return_exceptions=True)
        logging.info(f"Flushing metrics")


    loop = asyncio.get_event_loop()
    for s in (signal.SIGHUP, signal.SIGTERM, signal.SIGINT):
        print(f"Handling {s} ...")
        loop.add_signal_handler(s, lambda s=s: asyncio.create_task(_signal_handler(s, loop)))

    loop.run_until_complete(
        serve(app, config, shutdown_trigger=shutdown_event.wait)
    )

if __name__ == "__main__":
    main()
```

When I start this server like:
```
$ pipenv run python main.py
```

And target it with this `ab` test:
```
$ ab -n 100000 -c 4 http://localhost:9002/
This is ApacheBench, Version 2.3 <$Revision: 1903618 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 10000 requests
apr_socket_recv: Connection refused (61)
Total of 18376 requests completed
```

You can see that when I hit `CTRL+C` in the pipenv terminal, the `ab` execution correctly received a connection refused instead of `connection reset by peer`. I am not sure how to add this functionality to `hypercorn` so I can test with multiple processes/workers.

**Comment by nabheet** [comment]
LOL! and right after I posted the potential solution above, I am consistently getting `connection reset by peer` error. 🤣 

```
Benchmarking localhost (be patient)
Completed 10000 requests
apr_socket_recv: Connection reset by peer (54)
Total of 14011 requests completed
```

I give up! please help!!!!

**Comment by nabheet** [comment]
Ended up looking at tcpdump. Whenever I see a connection refused, I see 7 extra packets exchanged after the reply from the server. 

```
14:29:57.862484 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 167, bad cksum 0 (->3c4f)!)
    127.0.0.1.9002 > 127.0.0.1.49911: Flags [P.], cksum 0xfe9b (incorrect -> 0xcfa1), seq 714462272:714462387, ack 2460197520, win 6378, options [nop,nop,TS val 86037649 ecr 1367604424], length 115
	0x0000:  4500 00a7 0000 4000 4006 0000 7f00 0001  E.....@.@.......
	0x0010:  7f00 0001 232a c2f7 2a95 d440 92a3 a290  ....#*..*..@....
	0x0020:  8018 18ea fe9b 0000 0101 080a 0520 d491  ................
	0x0030:  5183 fcc8 4854 5450 2f31 2e31 2035 3030  Q...HTTP/1.1.500
	0x0040:  200d 0a63 6f6e 7465 6e74 2d6c 656e 6774  ...content-lengt
	0x0050:  683a 2030 0d0a 6461 7465 3a20 5468 752c  h:.0..date:.Thu,
	0x0060:  2031 3320 4a75 6e20 3230 3234 2032 303a  .13.Jun.2024.20:
	0x0070:  3239 3a35 3720 474d 540d 0a73 6572 7665  29:57.GMT..serve
	0x0080:  723a 2068 7970 6572 636f 726e 2d68 3131  r:.hypercorn-h11
	0x0090:  0d0a 436f 6e6e 6563 7469 6f6e 3a20 636c  ..Connection:.cl
	0x00a0:  6f73 650d 0a0d 0a                        ose....
14:29:57.862497 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 52, bad cksum 0 (->3cc2)!)
    127.0.0.1.49911 > 127.0.0.1.9002: Flags [.], cksum 0xfe28 (incorrect -> 0x1d34), seq 2460197520, ack 714462387, win 6377, options [nop,nop,TS val 1367604425 ecr 86037649], length 0
	0x0000:  4500 0034 0000 4000 4006 0000 7f00 0001  E..4..@.@.......
	0x0010:  7f00 0001 c2f7 232a 92a3 a290 2a95 d4b3  ......#*....*...
	0x0020:  8010 18e9 fe28 0000 0101 080a 5183 fcc9  .....(......Q...
	0x0030:  0520 d491                                ....
14:29:57.862534 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 52, bad cksum 0 (->3cc2)!)
    127.0.0.1.9002 > 127.0.0.1.49911: Flags [F.], cksum 0xfe28 (incorrect -> 0x1d32), seq 714462387, ack 2460197520, win 6378, options [nop,nop,TS val 86037649 ecr 1367604425], length 0
	0x0000:  4500 0034 0000 4000 4006 0000 7f00 0001  E..4..@.@.......
	0x0010:  7f00 0001 232a c2f7 2a95 d4b3 92a3 a290  ....#*..*.......
	0x0020:  8011 18ea fe28 0000 0101 080a 0520 d491  .....(..........
	0x0030:  5183 fcc9                                Q...
14:29:57.862552 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 52, bad cksum 0 (->3cc2)!)
    127.0.0.1.49911 > 127.0.0.1.9002: Flags [.], cksum 0xfe28 (incorrect -> 0x1d33), seq 2460197520, ack 714462388, win 6377, options [nop,nop,TS val 1367604425 ecr 86037649], length 0
	0x0000:  4500 0034 0000 4000 4006 0000 7f00 0001  E..4..@.@.......
	0x0010:  7f00 0001 c2f7 232a 92a3 a290 2a95 d4b4  ......#*....*...
	0x0020:  8010 18e9 fe28 0000 0101 080a 5183 fcc9  .....(......Q...
	0x0030:  0520 d491                                ....
14:29:57.862564 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 52, bad cksum 0 (->3cc2)!)
    127.0.0.1.49911 > 127.0.0.1.9002: Flags [F.], cksum 0xfe28 (incorrect -> 0x1d32), seq 2460197520, ack 714462388, win 6377, options [nop,nop,TS val 1367604425 ecr 86037649], length 0
	0x0000:  4500 0034 0000 4000 4006 0000 7f00 0001  E..4..@.@.......
	0x0010:  7f00 0001 c2f7 232a 92a3 a290 2a95 d4b4  ......#*....*...
	0x0020:  8011 18e9 fe28 0000 0101 080a 5183 fcc9  .....(......Q...
	0x0030:  0520 d491                                ....
14:29:57.862586 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 52, bad cksum 0 (->3cc2)!)
    127.0.0.1.9002 > 127.0.0.1.49911: Flags [.], cksum 0xfe28 (incorrect -> 0x1d31), seq 714462388, ack 2460197521, win 6378, options [nop,nop,TS val 86037649 ecr 1367604425], length 0
	0x0000:  4500 0034 0000 4000 4006 0000 7f00 0001  E..4..@.@.......
	0x0010:  7f00 0001 232a c2f7 2a95 d4b4 92a3 a291  ....#*..*.......
	0x0020:  8010 18ea fe28 0000 0101 080a 0520 d491  .....(..........
	0x0030:  5183 fcc9                                Q...
14:29:57.862593 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 64, bad cksum 0 (->3cb6)!)
    127.0.0.1.49912 > 127.0.0.1.9002: Flags [S], cksum 0xfe34 (incorrect -> 0xc12a), seq 3986137237, win 65535, options [mss 16344,nop,wscale 6,nop,nop,TS val 2316320586 ecr 0,sackOK,eol], length 0
	0x0000:  4500 0040 0000 4000 4006 0000 7f00 0001  E..@..@.@.......
	0x0010:  7f00 0001 c2f8 232a ed97 a095 0000 0000  ......#*........
	0x0020:  b002 ffff fe34 0000 0204 3fd8 0103 0306  .....4....?.....
	0x0030:  0101 080a 8a10 3f4a 0000 0000 0402 0000  ......?J........
14:29:57.862600 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 40, bad cksum 0 (->3cce)!)
    127.0.0.1.9002 > 127.0.0.1.49912: Flags [R.], cksum 0xfe1c (incorrect -> 0x3d7d), seq 0, ack 3986137238, win 0, length 0
	0x0000:  4500 0028 0000 4000 4006 0000 7f00 0001  E..(..@.@.......
	0x0010:  7f00 0001 232a c2f8 0000 0000 ed97 a096  ....#*..........
	0x0020:  5014 0000 fe1c 0000                      P.......
```

**Comment by nabheet** [comment]
here is what I "think" might be causing the issue. Looks like something in Python land is sending the reset on shutdown after the client has already initiated a connection and the server has acknowledged it. I have no idea how to fix it.

![image](https://github.com/pgjones/hypercorn/assets/1319809/e5535109-98ba-48f9-bdcc-7504f8d223b7)

**Comment by nabheet** [comment]
Firstly, I am sorry for going down this incorrect path regarding this problem. It turns out the root cause was our Python process was dying because of a segmentation fault.

Secondly, I found the issue by enabling [faulthandler](https://docs.python.org/3/library/faulthandler.html). This logged the exception stacktrace in the Cloud Run logs along with the HTTP503 error we have been investigating. So, if your python process is mysteriously disappearing, turn on the `faulthandler` and you will get all the information you need.

Now to the hard part of fixing the problem. 😄
