### ISSUE TITLE
error `hypercorn --config python:hypercorn_config.config`

### ISSUE THREAD

**Issue by taogya** [pgjones/hypercorn#244]
When I run `hypercorn --config python:hypercorn_config.config`, I get the following error:
(`hypercorn --config python:hypercorn_config.config` を実行すると次のエラーが出ます。)
```
  :
  File "/Users/xxxxx/venv/lib/python3.9/site-packages/hypercorn/config.py", line 406, in <dictcomp>
    if not isinstance(getattr(instance, key), types.ModuleType) and not key.startswith("__")
```

My hypercorn_config.py is the following:
(私のhypercorn_config.py は次のとおりです。)
```
config = Config()
config.bind = '0.0.0.0:8080'
```

Here is the result of the debug:
(デバッグした結果は以下の通りです。)
```
# debug code (breake point to hypercorn/config.py  line 406)
instance.cert_reqs
# debug code result
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: unreadable attribute
```

I'm not using cert_reqs, do I need to add the expression `config.cert_reqs = object()`?
(私はcert_reqsを使用しませんが、`config.cert_reqs = object()`という式を追加しなければなりませんか?)

If there's a smarter way, please let me know.
(もっと賢い方法があれば教えてください。)

**Comment by taogya** [comment]
I gave up on loading custom configs with the hypercorn command options, and now I run it with the following `asyncio.run(serve(app, config))`.
(hypercorn コマンドオプションでカスタムコンフィグをロードするのを諦め、現在は以下の`asyncio.run(serve(app, config))`にて実行するようにしています。)
https://hypercorn.readthedocs.io/en/latest/how_to_guides/api_usage.html
