### ISSUE TITLE
Task exception was never retrieved

### ISSUE THREAD

**Issue by jsiembida** [pgjones/hypercorn#26]
Hypercorn 0.9.0 sometimes raises the following exception. It is not fatal, but a bit concerning nonetheless.
```
Task exception was never retrieved
future: <Task finished coro=<worker_serve.<locals>._server_callback() done, defined at .../venv/lib/python3.7/site-packages/hypercorn/asyncio/run.py:88> exception=AttributeError("'NoneType' object has no attribute 'handle'")>
Traceback (most recent call last):
  File ".../venv/lib/python3.7/site-packages/hypercorn/asyncio/run.py", line 89, in _server_callback
    await TCPServer(app, loop, config, reader, writer)
  File ".../venv/lib/python3.7/site-packages/hypercorn/asyncio/tcp_server.py", line 75, in run
    await self._read_data()
  File ".../venv/lib/python3.7/site-packages/hypercorn/asyncio/tcp_server.py", line 102, in _read_data
    await self.protocol.handle(RawData(data))
  File ".../venv/lib/python3.7/site-packages/hypercorn/protocol/__init__.py", line 63, in handle
    return await self.protocol.handle(event)
  File ".../venv/lib/python3.7/site-packages/hypercorn/protocol/h11.py", line 108, in handle
    await self._handle_events()
  File ".../venv/lib/python3.7/site-packages/hypercorn/protocol/h11.py", line 168, in _handle_events
    await self.stream.handle(event)
AttributeError: 'NoneType' object has no attribute 'handle'
```

**Comment by pgjones** [comment]
I think this is fixed in 0.9.2, could you check?
