### ISSUE TITLE
ImportError: cannot import name 'TaskGroup' from 'asyncio' on Python 3.8.2

### ISSUE THREAD

**Issue by RLThomasPremfina** [pgjones/hypercorn#270]
We are running a FastAPI microservice using hypercorn 0.17.3 which states it is python 3.8 compatible.
The following exception occurs as hypercord is atempting to use asyncio TaskGroups which are introduced in python 3.11.

Can you investigate and advise solution please

Traceback (most recent call last):
  File "/home/pf_system_apps/applications/be__bank_checker_experian/releases/0.0.47/.venv/bin/hypercorn", line 8, in <module>
    sys.exit(main())
  File "/home/pf_system_apps/applications/be__bank_checker_experian/releases/0.0.47/.venv/lib/python3.8/site-packages/hypercorn/__main__.py", line 304, in main
    return run(config)
  File "/home/pf_system_apps/applications/be__bank_checker_experian/releases/0.0.47/.venv/lib/python3.8/site-packages/hypercorn/run.py", line 25, in run
    from .asyncio.run import asyncio_worker
  File "/home/pf_system_apps/applications/be__bank_checker_experian/releases/0.0.47/.venv/lib/python3.8/site-packages/hypercorn/asyncio/__init__.py", line 6, in <module>
    from .run import worker_serve
  File "/home/pf_system_apps/applications/be__bank_checker_experian/releases/0.0.47/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 17, in <module>
    from .tcp_server import TCPServer
  File "/home/pf_system_apps/applications/be__bank_checker_experian/releases/0.0.47/.venv/lib/python3.8/site-packages/hypercorn/asyncio/tcp_server.py", line 7, in <module>
    from .task_group import TaskGroup
  File "/home/pf_system_apps/applications/be__bank_checker_experian/releases/0.0.47/.venv/lib/python3.8/site-packages/hypercorn/asyncio/task_group.py", line 14, in <module>
    from taskgroup import TaskGroup as AsyncioTaskGroup  # type: ignore
  File "/home/pf_system_apps/applications/be__bank_checker_experian/releases/0.0.47/.venv/lib/python3.8/site-packages/taskgroup/__init__.py", line 9, in <module>
    from .runners import run, Runner
  File "/home/pf_system_apps/applications/be__bank_checker_experian/releases/0.0.47/.venv/lib/python3.8/site-packages/taskgroup/runners.py", line 22, in <module>
    from .tasks import task_factory as _task_factory
  File "/home/pf_system_apps/applications/be__bank_checker_experian/releases/0.0.47/.venv/lib/python3.8/site-packages/taskgroup/tasks.py", line 18, in <module>
    _TaskYieldType: TypeAlias = Optional[asyncio.Future[object]]
TypeError: 'type' object is not subscriptable
Traceback (most recent call last):
  File "/home/pf_system_apps/applications/be__bank_checker_experian/releases/0.0.47/.venv/lib/python3.8/site-packages/hypercorn/asyncio/task_group.py", line 12, in <module>
    from asyncio import TaskGroup as AsyncioTaskGroup
ImportError: cannot import name 'TaskGroup' from 'asyncio' (/home/pf_system_apps/.pyenv/versions/3.8.2/lib/python3.8/asyncio/__init__.py)

**Comment by roys10** [comment]
You are correct, I also encountered it. If you cannot use a newer python version you can use an older version of hypercorn - 0.14.4 and below will work.

**Comment by pgjones** [comment]
Yep, Python 3.8 has reached end of life and is no longer supported.
