### ISSUE TITLE
LifespanTimeout: Timeout whilst awaiting startup. Your application may not support the ASGI Lifespan protocol correctly, alternatively the startup_timeout configuration is incorrect.

### ISSUE THREAD

**Issue by Yandawl** [pgjones/hypercorn#28]
Hi, I'm using Quart 0.11.3 with Hypercorn 0.9.2.

My application is timing out on the @app.before_serving because I'm trying to connect to Redis on another server which is firewalled against my access so there is valid reason for it to be timing out however I get the following error: 

LifespanTimeout: Timeout whilst awaiting startup. Your application may not support the ASGI Lifespan protocol correctly, alternatively the startup_timeout configuration is incorrect.

Just thought you should be aware.

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
Process Process-1:
  File "/usr/local/lib/python3.7/dist-packages/hypercorn/asyncio/run.py", line 193, in uvloop_worker
    shutdown_trigger=shutdown_trigger,
  File "/usr/local/lib/python3.7/dist-packages/hypercorn/asyncio/run.py", line 223, in _run
    loop.run_until_complete(main(shutdown_trigger=shutdown_trigger))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/dist-packages/hypercorn/asyncio/run.py", line 62, in worker_serve
    await lifespan.wait_for_startup()
  File "/usr/local/lib/python3.7/dist-packages/hypercorn/asyncio/lifespan.py", line 54, in wait_for_startup
    raise LifespanTimeout("startup") from error
hypercorn.utils.LifespanTimeout: Timeout whilst awaiting startup. Your application may not support the ASGI Lifespan protocol correctly, alternatively the startup_timeout configuration is incorrect.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/hypercorn/asyncio/lifespan.py", line 52, in wait_for_startup
    await asyncio.wait_for(self.startup.wait(), timeout=self.config.startup_timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/hypercorn/asyncio/run.py", line 193, in uvloop_worker
    shutdown_trigger=shutdown_trigger,
  File "/usr/local/lib/python3.7/dist-packages/hypercorn/asyncio/run.py", line 223, in _run
    loop.run_until_complete(main(shutdown_trigger=shutdown_trigger))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/dist-packages/hypercorn/asyncio/run.py", line 62, in worker_serve
    await lifespan.wait_for_startup()
  File "/usr/local/lib/python3.7/dist-packages/hypercorn/asyncio/lifespan.py", line 54, in wait_for_startup
    raise LifespanTimeout("startup") from error
hypercorn.utils.LifespanTimeout: Timeout whilst awaiting startup. Your application may not support the ASGI Lifespan protocol correctly, alternatively the startup_timeout configuration is incorrect.
```

**Comment by pgjones** [comment]
Hi @Yandawl, this error is meant to make you aware that there is an issue in your own code. I don't think it is as clear as I'd hope though (given this issue). Could you suggest a clearer wording?
