### ISSUE TITLE
Deprecated --uvloop option is broken in 4.0.0

### ISSUE THREAD

**Issue by dimaqq** [pgjones/hypercorn#5]
`--uvloop` is documented as deprecated, option is accepted by command line argument parser, but causes a crash:

```
> hypercorn --uvloop some_module
Running on http://127.0.0.1:5000 (CTRL + C to quit)
Traceback (most recent call last):
  File "/Users/.../hypercorn", line 11, in <module>
    sys.exit(main())
  File "/Users/.../hypercorn/__main__.py", line 162, in main
    run(config)
  File "/Users/.../hypercorn/run.py", line 28, in run
    raise ValueError(f"No worker of class {config.worker_class} exists")
ValueError: No worker of class <object object at 0x105abe550> exists
```

Meanwhile new syntax works:

```
> hypercorn --worker-class uvloop some_module
Running on http://127.0.0.1:5000 (CTRL + C to quit)
```

Perhaps updating the docs is enough.

**Comment by pgjones** [comment]
Thanks, I've fixed in e2d3ff851ccc017caa3f1be6c17da669d3f93b80
