### ISSUE TITLE
Exception thrown in docker container!

### ISSUE THREAD

**Issue by khteh** [pgjones/hypercorn#57]
```
2022-06-09 08:00:39 ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-386' coro=<worker_serve.<locals>._server_callback() done, defined at /usr/local/lib/python3.10/site-packages/hypercorn/asyncio/run.py:98> wait_for=<_GatheringFuture pending cb=[Task.__wakeup()]>>
2022-06-09 08:00:39 ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-387' coro=<H2Protocol.send_task() done, defined at /usr/local/lib/python3.10/site-packages/hypercorn/protocol/h2.py:140> wait_for=<Future cancelled> cb=[gather.<locals>._done_callback() at /usr/local/lib/python3.10/asyncio/tasks.py:720]>
Exception ignored in: <coroutine object worker_serve.<locals>._server_callback at 0x7fcbc9157990>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hypercorn/asyncio/run.py", line 100, in _server_callback
    await TCPServer(app, loop, config, context, reader, writer)
  File "/usr/local/lib/python3.10/site-packages/hypercorn/asyncio/tcp_server.py", line 70, in run
    async with TaskGroup(self.loop) as task_group:
RuntimeError: coroutine ignored GeneratorExit
2022-06-09 08:00:39 ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-392' coro=<worker_serve.<locals>._server_callback() done, defined at /usr/local/lib/python3.10/site-packages/hypercorn/asyncio/run.py:98> wait_for=<_GatheringFuture pending cb=[Task.__wakeup()]>>
2022-06-09 08:00:39 ERROR    Task was destroyed but it is pending!
task: <Task pending name='Task-394' coro=<H2Protocol.send_task() done, defined at /usr/local/lib/python3.10/site-packages/hypercorn/protocol/h2.py:140> wait_for=<Future cancelled> cb=[gather.<locals>._done_callback() at /usr/local/lib/python3.10/asyncio/tasks.py:720]>
```

**Comment by pgjones** [comment]
These usually indicate that a task has been cancelled and not awaited. I think I managed to find all these in Hypercorn so I'd suspect elsewhere - do you have an idea where this could happen?

**Comment by pgjones** [comment]
Needs more information to investigate.
