### ISSUE TITLE
QUART.app.run() throw a exception when it runing in a subthread.

### ISSUE THREAD

**Issue by Iualeby** [pgjones/hypercorn#6]
In Hypercorn==0.3.2, QUART.app.run() could working normal in a thread.
In Hypercorn==0.4.1 or 0.4.2, QUART.app.run() throw a exception when it runing in a subthread.
So I can't use the newest Hypercorn and insteading of running ""pip --upgrade Hypercorn==0.3.2" 

Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Program Files\Python3.7.1\Lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python3.7.1\Lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "./demo.py", line 196, in loop
    app.run(debug=False,host='0.0.0.0',port=port)
  File "C:\Program Files\Python3.7.1\lib\site-packages\quart\app.py", line 1337, in run
    run_single(self, config, loop=loop)
  File "C:\Program Files\Python3.7.1\lib\site-packages\hypercorn\asyncio\run.py", line 150, in run_single
    signal.signal(getattr(signal, signal_name), _raise_shutdown)
  File "C:\Program Files\Python3.7.1\Lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

**Comment by pgjones** [comment]
Hmm, I hadn't considered that someone would want to do this. What is it that you are trying to do? (Are you aware of [these decorators](https://pgjones.gitlab.io/quart/startup_shutdown.html) as I think they may solve your problem).

**Comment by Iualeby** [comment]
I have something importable to do in main thread, just like user-interface.So I want to run QUART app in background thread.
I don't know which decorator may solve my problem , could you tell me if you are free. ^_^

**Comment by pgjones** [comment]
Well you could always run the other thing in another thread and keep Quart on the main thread, e.g.
```
@app.before_serving
async def startup():
    app.background_thread = ...

@app.after_serving
async def shutdown():
    app.background_thread.join(1)
```
